### ISSUE TITLE
Failed to load audio: [WinError 2] The specified file can not be found

### ISSUE THREAD

**Issue by QuickLike** [JarodMica/rvc-tts-pipeline#7]
Trying to convert with rvc_convert, but it fails and got me this Exception:
```
`Traceback (most recent call last):
  File "f:\python\py\tts\venv\src\rvc\lib\audio.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\Python\py\TTS\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "F:\Python\py\TTS\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\Quick\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Quick\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\py\TTS\main.py", line 47, in <module>
    rvc_convert(model_path='eduard.pth',
  File "f:\python\py\tts\venv\src\rvc-tts-pipe\rvc_infer.py", line 323, in rvc_convert
    wav_opt=vc_single(0,input_path,f0_up_key,None,f0method,file_index,file_index2,index_rate,filter_radius,resample_sr,rms_mix_rate,protect)
  File "f:\python\py\tts\venv\src\rvc-tts-pipe\rvc_infer.py", line 160, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "f:\python\py\tts\venv\src\rvc\lib\audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] Не удается найти указанный файл`
```
I read that other people had the same error. I need to do something with ffmpeg, but nothing works for me. Python 3.10

Tried to reinstall ffmpeg. Not working. Trying to use other Python versions. Not working. Trying to extract ffmpeg.exe from this archive https://github.com/BtbN/FFmpeg-Builds/releases into ffmpge library folder. Not working

**Comment by JarodMica** [comment]
Can you extract the ffmpeg.exe and place it in the same directory as wherever you're running your script from?  This should allow you're computer to see ffmpeg regardless of whether or not it's installed
