### ISSUE TITLE
Error occurs when specifying custom output directory: PermissionError: [Errno 13] Permission denied: 'outputs\\rvc_out'

### ISSUE THREAD

**Issue by Mechanism8** [JarodMica/rvc-tts-pipeline#9]
Hi! I am facing this error when trying to input a custom output_path_dir:

`Traceback (most recent call last):
  File "C:\Users\Mech8\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mech8\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Mech8\.vscode\extensions\ms-python.python-2023.20.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "F:\xtts-webui\rvc_client.py", line 4, in <module>
    rvc_convert(
  File "F:\xtts-webui\.venv\src\rvc-tts-pipe\rvc_infer.py", line 324, in rvc_convert
    wavfile.write(output_file_path, tgt_sr, wav_opt)
  File "f:\xtts-webui\.venv\lib\site-packages\scipy\io\wavfile.py", line 767, in write
    fid = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'outputs\\rvc_out'`

This happens with windows-like and unix-like paths (like 'outputs\rvc_out' for example) and adding the file name to path doesn't work as well. Just in case I applied full permissions to the output directories, but this doesn't help. Could you please take a look?

**Comment by GlobalMeltdown** [comment]
Similar issue as well too

`Model Path: C:\Users\thegl\OneDrive\Desktop\Python\assets\weights\hubert_base.pt
Audio File: path to audio file
Output Directory:
2024-10-20 19:53:51 | INFO | comtypes.client._code_cache | Imported existing <module 'comtypes.gen' from 'C:\\Users\\thegl\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\comtypes\\gen\\__init__.py'>
2024-10-20 19:53:51 | INFO | comtypes.client._code_cache | Using writeable comtypes cache directory: 'C:\Users\thegl\AppData\Local\Programs\Python\Python310\lib\site-packages\comtypes\gen'
Loading HuBERT model from: C:\Users\thegl\OneDrive\Desktop\Python\assets\weights\hubert_base.pt
2024-10-20 19:53:51 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\Users\thegl\OneDrive\Desktop\Python
2024-10-20 19:53:51 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-10-20 19:53:51 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
loading pth C:\Users\thegl\OneDrive\Desktop\Python\assets\weights\model.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
loading rmvpe model
Error in RVC speech generation: [Errno 13] Permission denied: 'rvc_output'`

also I noticed if you place the the hubert and rvmpe any other directory besides the root of your project regardless of what directory paths you setup in your script or the yaml it will not load them.

bump
